# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

# Restaurar SOLO el proyecto principal (no la solución)
RUN dotnet restore ProjectFinally/ProjectFinally.csproj

# Publicar el proyecto principal
RUN dotnet publish ProjectFinally/ProjectFinally.csproj -c Release -o /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "ProjectFinally.dll"]
